---
# handlers file for roles/ansible_role_deploy_dockercompose

- name: Deploy stack
  community.docker.docker_compose_v2:
    project_src: "{{ path_to_composefile }}"
    project_name: "{{ stack_name }}"
    recreate: always 

